// tslint:disable
/**
 * AstroPlant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, HttpHeaders, throwIfNullOrUndefined } from '../runtime';
import {
    AuthRefreshToken,
    AuthUser,
    AuthenticationTokens,
    FullUser,
    ProblemInternalServer,
    ProblemInvalidParameters,
    ProblemRateLimit,
} from '../models';

export interface AuthenticateByCredentialsRequest {
    authUser: AuthUser;
}

export interface ObtainAccessTokenFromRefreshTokenRequest {
    authRefreshToken: AuthRefreshToken;
}

/**
 * no description
 */
export class AccessApi extends BaseAPI {

    /**
     * Authenticate yourself by username and password.
     */
    authenticateByCredentials = ({ authUser }: AuthenticateByCredentialsRequest): Observable<AuthenticationTokens> => {
        throwIfNullOrUndefined(authUser, 'authenticateByCredentials');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<AuthenticationTokens>({
            path: '/me/auth',
            method: 'POST',
            headers,
            body: authUser,
        });
    };

    /**
     * Obtain an access token from a refresh token.
     */
    obtainAccessTokenFromRefreshToken = ({ authRefreshToken }: ObtainAccessTokenFromRefreshTokenRequest): Observable<string> => {
        throwIfNullOrUndefined(authRefreshToken, 'obtainAccessTokenFromRefreshToken');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<string>({
            path: '/me/refresh',
            method: 'POST',
            headers,
            body: authRefreshToken,
        });
    };

    /**
     * Your user information.
     */
    showMe = (): Observable<FullUser> => {
        const headers: HttpHeaders = {
            ...(this.configuration.username != null && this.configuration.password != null ? { Authorization: `Basic ${btoa(this.configuration.username + ':' + this.configuration.password)}` } : undefined),
        };

        return this.request<FullUser>({
            path: '/me',
            method: 'GET',
            headers,
        });
    };

}
