// tslint:disable
/**
 * AstroPlant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, HttpQuery } from '../runtime';
import {
    PeripheralDefinition,
    ProblemInternalServer,
    ProblemRateLimit,
    QuantityType,
} from '../models';

export interface ListPeripheralDefinitionsRequest {
    after?: number;
    withExpectedQuantityTypes?: boolean;
}

export interface ListQuantityTypesRequest {
    after?: number;
}

/**
 * no description
 */
export class DefinitionsApi extends BaseAPI {

    /**
     * List all peripheral device definitions.
     */
    listPeripheralDefinitions = ({ after, withExpectedQuantityTypes }: ListPeripheralDefinitionsRequest): Observable<Array<PeripheralDefinition>> => {

        const query: HttpQuery = {};

        if (after != null) { query['after'] = after; }
        if (withExpectedQuantityTypes != null) { query['withExpectedQuantityTypes'] = withExpectedQuantityTypes; }

        return this.request<Array<PeripheralDefinition>>({
            path: '/peripheral-definitions',
            method: 'GET',
            query,
        });
    };

    /**
     * List all quantity types.
     */
    listQuantityTypes = ({ after }: ListQuantityTypesRequest): Observable<Array<QuantityType>> => {

        const query: HttpQuery = {};

        if (after != null) { query['after'] = after; }

        return this.request<Array<QuantityType>>({
            path: '/quantity-types',
            method: 'GET',
            query,
        });
    };

}
