// tslint:disable
/**
 * AstroPlant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, HttpHeaders, throwIfRequired, encodeURI } from '../runtime';
import {
    InlineResponse429,
    InlineResponse500,
} from '../models';

export interface UptimeRequest {
    kitSerial: string;
}

export interface VersionRequest {
    kitSerial: string;
}

/**
 * no description
 */
export class KitRpcApi extends BaseAPI {

    /**
     * Query the kit for its uptime.
     */
    uptime = (requestParameters: UptimeRequest): Observable<number> => {
        throwIfRequired(requestParameters, 'kitSerial', 'uptime');

        const headers: HttpHeaders = {
            ...(this.configuration.username && this.configuration.password && { Authorization: `Basic ${btoa(this.configuration.username + ':' + this.configuration.password)}` }),
        };

        return this.request<number>({
            path: '/kit-rpc/{kitSerial}/uptime'.replace('{kitSerial}', encodeURI(requestParameters.kitSerial)),
            method: 'GET',
            headers,
        });
    };

    /**
     * Query the kit for the version it is running.
     */
    version = (requestParameters: VersionRequest): Observable<string> => {
        throwIfRequired(requestParameters, 'kitSerial', 'version');

        const headers: HttpHeaders = {
            ...(this.configuration.username && this.configuration.password && { Authorization: `Basic ${btoa(this.configuration.username + ':' + this.configuration.password)}` }),
        };

        return this.request<string>({
            path: '/kit-rpc/{kitSerial}/version'.replace('{kitSerial}', encodeURI(requestParameters.kitSerial)),
            method: 'GET',
            headers,
        });
    };

}
