// tslint:disable
/**
 * AstroPlant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, HttpHeaders } from '../runtime';
import {
    FullUser,
    InlineResponse429,
    InlineResponse500,
    KitMembership,
} from '../models';

/**
 * no description
 */
export class MeApi extends BaseAPI {

    /**
     * Your user information.
     */
    showMe = (): Observable<FullUser> => {
        const headers: HttpHeaders = {
            ...(this.configuration.username && this.configuration.password && { Authorization: `Basic ${btoa(this.configuration.username + ':' + this.configuration.password)}` }),
        };

        return this.request<FullUser>({
            path: '/me',
            method: 'GET',
            headers,
        });
    };

    /**
     * Your kit memberships.
     */
    showMyKitMemberships = (): Observable<Array<KitMembership>> => {
        const headers: HttpHeaders = {
            ...(this.configuration.username && this.configuration.password && { Authorization: `Basic ${btoa(this.configuration.username + ':' + this.configuration.password)}` }),
        };

        return this.request<Array<KitMembership>>({
            path: '/me/memberships',
            method: 'GET',
            headers,
        });
    };

}
