// tslint:disable
/**
 * AstroPlant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface FullUser
 */
export interface FullUser {
    /**
     * @type {number}
     * @memberof FullUser
     */
    id: number;
    /**
     * @type {string}
     * @memberof FullUser
     */
    username: string;
    /**
     * @type {string}
     * @memberof FullUser
     */
    displayName: string;
    /**
     * @type {string}
     * @memberof FullUser
     */
    emailAddress: string;
    /**
     * @type {boolean}
     * @memberof FullUser
     */
    useEmailAddressForGravatar: boolean;
    /**
     * @type {string}
     * @memberof FullUser
     */
    gravatarAlternative: string;
}
