// tslint:disable
/**
 * AstroPlant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface InlineObject2
 */
export interface InlineObject2 {
    /**
     * @type {string}
     * @memberof InlineObject2
     */
    username: string;
    /**
     * @type {string}
     * @memberof InlineObject2
     */
    password: string;
}
