// tslint:disable
/**
 * AstroPlant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface InlineResponse500
 */
export interface InlineResponse500 {
    /**
     * The error code for internal server errors: 1
     * @type {number}
     * @memberof InlineResponse500
     */
    errorCode?: number;
    /**
     * The error name for internal server errors: internalServer
     * @type {string}
     * @memberof InlineResponse500
     */
    errorName?: string;
}
