// tslint:disable
/**
 * AstroPlant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface InlineObject
 */
export interface InlineObject {
    /**
     * @type {string}
     * @memberof InlineObject
     */
    name?: string;
    /**
     * @type {string}
     * @memberof InlineObject
     */
    description?: string;
    /**
     * @type {number}
     * @memberof InlineObject
     */
    latitude?: number;
    /**
     * @type {number}
     * @memberof InlineObject
     */
    longitude?: number;
    /**
     * @type {boolean}
     * @memberof InlineObject
     */
    privacyPublicDashboard: boolean;
    /**
     * @type {boolean}
     * @memberof InlineObject
     */
    privacyShowOnMap: boolean;
}
