// tslint:disable
/**
 * AstroPlant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    KitConfiguration,
    KitConfigurationWithPeripheralsAllOf,
    Peripheral,
} from './';

/**
 * @export
 * @interface KitConfigurationWithPeripherals
 */
export interface KitConfigurationWithPeripherals {
    /**
     * @type {number}
     * @memberof KitConfigurationWithPeripherals
     */
    id: number;
    /**
     * @type {number}
     * @memberof KitConfigurationWithPeripherals
     */
    kitId: number;
    /**
     * @type {string}
     * @memberof KitConfigurationWithPeripherals
     */
    description?: string;
    /**
     * @type {boolean}
     * @memberof KitConfigurationWithPeripherals
     */
    active: boolean;
    /**
     * @type {boolean}
     * @memberof KitConfigurationWithPeripherals
     */
    neverUsed: boolean;
    /**
     * @type {Array<Peripheral>}
     * @memberof KitConfigurationWithPeripherals
     */
    peripherals?: Array<Peripheral>;
}
