// tslint:disable
/**
 * AstroPlant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface KitConfiguration
 */
export interface KitConfiguration {
    /**
     * @type {number}
     * @memberof KitConfiguration
     */
    id: number;
    /**
     * @type {number}
     * @memberof KitConfiguration
     */
    kitId: number;
    /**
     * @type {string}
     * @memberof KitConfiguration
     */
    description?: string;
    /**
     * @type {boolean}
     * @memberof KitConfiguration
     */
    active: boolean;
    /**
     * @type {boolean}
     * @memberof KitConfiguration
     */
    neverUsed: boolean;
}
