// tslint:disable
/**
 * AstroPlant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Kit,
} from './';

/**
 * @export
 * @interface KitMembership
 */
export interface KitMembership {
    /**
     * @type {number}
     * @memberof KitMembership
     */
    id: number;
    /**
     * @type {number}
     * @memberof KitMembership
     */
    user: number;
    /**
     * @type {Kit}
     * @memberof KitMembership
     */
    kit: Kit;
    /**
     * @type {boolean}
     * @memberof KitMembership
     */
    accessConfigure: boolean;
    /**
     * @type {boolean}
     * @memberof KitMembership
     */
    accessSuper: boolean;
    /**
     * @type {Date}
     * @memberof KitMembership
     */
    datetimeLinked: Date;
}
