// tslint:disable
/**
 * AstroPlant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface NewUser
 */
export interface NewUser {
    /**
     * @type {string}
     * @memberof NewUser
     */
    username: string;
    /**
     * @type {string}
     * @memberof NewUser
     */
    password: string;
    /**
     * @type {string}
     * @memberof NewUser
     */
    emailAddress: string;
}
