// tslint:disable
/**
 * AstroPlant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface PatchKitConfiguration
 */
export interface PatchKitConfiguration {
    /**
     * @type {string}
     * @memberof PatchKitConfiguration
     */
    description?: string;
    /**
     * @type {string}
     * @memberof PatchKitConfiguration
     */
    controllerSymbolLocation?: string;
    /**
     * @type {string}
     * @memberof PatchKitConfiguration
     */
    controllerSymbol?: string;
    /**
     * @type {object}
     * @memberof PatchKitConfiguration
     */
    controlRules?: object;
    /**
     * @type {boolean}
     * @memberof PatchKitConfiguration
     */
    active?: boolean;
}
