// tslint:disable
/**
 * AstroPlant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ProblemRateLimitErrorValue,
} from './';

/**
 * @export
 * @interface ProblemRateLimit
 */
export interface ProblemRateLimit {
    /**
     * The error code for rate limit errors: 2
     * @type {number}
     * @memberof ProblemRateLimit
     */
    errorCode?: number;
    /**
     * The error name for rate limit errors: rateLimit
     * @type {string}
     * @memberof ProblemRateLimit
     */
    errorName?: string;
    /**
     * @type {ProblemRateLimitErrorValue}
     * @memberof ProblemRateLimit
     */
    errorValue?: ProblemRateLimitErrorValue;
}
