// tslint:disable
/**
 * AstroPlant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A basic problem report, conforming to RFC7807. Most problems will provide additional fields with information.
 * @export
 * @interface ProblemDetails
 */
export interface ProblemDetails {
    /**
     * @type {string}
     * @memberof ProblemDetails
     */
    type?: string;
    /**
     * @type {string}
     * @memberof ProblemDetails
     */
    title?: string;
    /**
     * @type {number}
     * @memberof ProblemDetails
     */
    status?: number;
    /**
     * @type {string}
     * @memberof ProblemDetails
     */
    detail?: string;
}
