// tslint:disable
/**
 * AstroPlant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface QuantityType
 */
export interface QuantityType {
    /**
     * @type {number}
     * @memberof QuantityType
     */
    id: number;
    /**
     * @type {string}
     * @memberof QuantityType
     */
    physicalQuantity: string;
    /**
     * @type {string}
     * @memberof QuantityType
     */
    physicalUnit: string;
    /**
     * @type {string}
     * @memberof QuantityType
     */
    physicalUnitSymbol?: string;
}
